config/routes.rb
Digginit::Application.routes.draw do

  get "collaborations/index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  
  resources :users
  resources :email_confirmations
  resources :charges
  resources :wikis do
    resources :collaborations, controller: 'wikis/collaborations' 
  end

  root to: 'welcome#index'
  match "about" => 'welcome#about', via: :get 

  

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :email, :password, :password_confirmation, :confirmed_at, :account
  before_save :update_slug
  has_secure_password
  has_many :collaborations
  has_many :wikis, :through => :collaborations

  ACCOUNTS = %w[member premium admin]
  def account?(base_account)
    account.nil? ? false : ACCOUNTS.index(base_account.to_s) <= ACCOUNTS.index(account)
  end 

  def update_slug
    self.slug = self.name.parameterize
  end

  def to_param
    self.slug
    # self.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @account = params[:account]
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by_slug(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      @user.update_attribute(:token, SecureRandom.hex(6))
      RegistrationMailer.registration_confirmation(@user, new_email_confirmation_url(token: @user.token)).deliver
      if( @user.account == "premium")
        redirect_to new_charge_path :user, @user
      else
        redirect_to root_path, notice: "An email has been sent to your account. Please click the link in the email to verify address and complete your registration."
      end
    else
      flash[:error] = "Error creating new user. Please try again."
      render :new
    end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
     @user = User.find_by_slug(params[:id])
     # @wiki = Wiki.find(params[:id])
     # merge default value with params so if no collaborators checked, will erase
     if @user.update_attributes(params[:user])
       redirect_to @user
     else
       flash[:error] = "Error saving user.  Please try again."
       render :edit
     end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_slug(params[:id])
    end

    # Never trust parameters from the internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :account)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>
      <div class="field">
        <%= f.label :name, 'Name:' %><br>
        <%= f.text_field :name, size: 40, placeholder: "full name", required: true %>
      </div>
      <div class="field">
        <%= f.label :email, 'Email:' %><br>
        <%= f.email_field :email, size: 40, placeholder: "email address", required: true  %>
      </div>
      <div class="field">
        <%= f.label :password, 'Password:' %><br>
        <%= f.password_field :password, size:40, placeholder: "password", required: true  %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, 'Confirm password:' %><br>
        <%= f.password_field :password_confirmation, size: 40, placeholder: "confirm password", required: true  %>
      </div>
      <%= f.hidden_field :account, :value => @user.account %>
      <div class="actions">
        <%= f.submit %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>all users</h1>
<% if notice %>
  <p id="notice"><%= notice %> </p>
<%end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h3><%= "register for your #{@user.account} digginIt account:" %></h3><br>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table id="users" class="bordered">
  <tr>
    <td><strong>name:</strong></td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td><strong>e-mail:</strong></td>
    <td><%= @user.email%></td>
  </tr>
  <tr>
    <td><strong>account type:</strong></td>
    <td><%= @user.account%></td>
  </tr>
  <tr>
    <td><strong>member since:</strong></td>
    <td><%= @user.created_at%></td>
  </tr>
</table>
<br>
<br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<% if @user.account == "member" %>
  | <%= link_to 'Upgrade to a Premium Account', new_charge_path %>
<% end %>