config/routes.rb
Digginit::Application.routes.draw do

  get "collaborations/index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  
  resources :users
  resources :email_confirmations
  resources :charges
  resources :wikis do
    resources :collaborations, controller: 'wikis/collaborations' 
  end

  root to: 'welcome#index'
  match "about" => 'welcome#about', via: :get 

  

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessible :title, :body, :public, :user_id, :user_ids
  before_save :update_slug

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true

  has_many :collaborations
  has_many :users, :through => :collaborations

  default_scope order('title ASC')
  scope :visible_to, lambda { |user| user.account == 'admin' ? scoped : Wiki.includes(:collaborations).where("wikis.public = true OR wikis.user_id = ? OR collaborations.user_id = ?", user.id, user.id) }
  # scope :visible_to, lambda { |user| user.role == 'admin' ? scoped : joins(:collaborators).where("wikis.public = true OR wikis.user_id = ? OR wikis.collaborators.user_id = ?", user.id, user.id) }
  # scope :visible_to, lambda { |user| user.account == 'admin' ? scoped : Wiki.where('public=true OR user_id = ?', user.id)}

  def update_slug
    self.slug = self.title.parameterize
  end

  def to_param
    self.slug
    # self.id
  end
end

app/controllers/wikis/collaborations_controller.rb
class Wikis::CollaborationsController < ApplicationController
  def index
    @wiki = Wiki.find(params[:wiki_id])
    @collaborations = Collaboration.all
    @users = User.all
  end

  def create
    # @wiki = Wiki.find_by_slug(params[:wiki_id])
    @wiki = Wiki.find(params[:wiki_id])
    @collaboration = Collaboration.new(params[:collaboration])
    if @collaboration.save
      flash[:notice] = "Collaboration was saved successfully."
      redirect_to wikis_path
    else
      flash[:error] = "Error creating collaboration. Please try again."
      render :new
    end
  end  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.visible_to(current_user)
  end

  def new
    @wiki = Wiki.new
    @wiki.user_id = current_user.id

  end

  def show
    @wiki = Wiki.find_by_slug(params[:id])
    @author = User.find(@wiki.user_id)
    # @wiki = Wiki.find(params[:id])
    current_user.cur_wiki = @wiki.id
    current_user.save
  end

  def edit
    @wiki = Wiki.find_by_slug(params[:id])
    # @wiki = Wiki.find(params[:id])
    authorize! :update, @wiki, message: "You don't have access to edit this wiki."
  end

  def create
    @wiki = Wiki.new(params[:wiki])
    authorize! :create, @wiki, message: "You need to register for a Free account to create Public wikis, or a Premium account to create Priviate wikis."
    @wiki.user_id = current_user.id
    # assign user to wiki in collaborator and set wiki role = admin
    if @wiki.save
      flash[:notice] = "Wiki was created successfully."
      redirect_to @wiki
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

   def update
     @wiki = Wiki.find_by_slug(params[:id])
     # @wiki = Wiki.find(params[:id])
     # merge default value with params so if no collaborators checked, will erase
     @wiki.attributes = {'user_ids' => []}.merge(params[:wiki] || {})
     authorize! :update, @wiki, message: "You don't have access to this wiki to update it."
     if @wiki.update_attributes(params[:wiki])
       redirect_to @wiki
     else
       flash[:error] = "Error saving wiki.  Please try again."
       render :edit
     end
   end

  def destroy
    @wiki = Wiki.find_by_slug(params[:id])
    # @wiki = Wiki.find(params[:id])
    title = @wiki.title
    authorize! :destroy, @wiki, message: "You don't have acccess to delete this wiki."
    if @wiki.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to root_path
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/edit.html.erb
<div class="sixteen columns clearfix">
  <div class="eight columns alpha">
    <h1>edit wiki:</h1>
  </div>
  <div class="eight columns omega">
    <h1>wiki preview:</h1><br>
  </div>
</div>

<div class="sixteen columns clearfix">
  <div class="eight columns alpha">
    <%= form_for @wiki, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title , id: 'js-wikititle'%>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :body, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :body, id: 'js-wikibody', rows: 8 %>
        </div>
      </div>

      <% if can? :create_private, Wiki %>
        <div class="control-group">
          <div class="controls">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private, :checked => !@wiki.public %>make this private wiki<br><br>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>  
    </div>

    <div class="eight columns omega">
      <div class="js-titlepreview">
        <h3><%= @wiki.title %></h3>
      </div>
      <div class="js-wikipreview">
        <p><%= markdown @wiki.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<h1><%= "#{current_user.name}'s wikis" %></h1>
<% if can? :create, Wiki %>
  <%= link_to "create new wiki", new_wiki_path, class: 'button' %>
<% end %>

<table id="wikis", class="bordered">
  <% @wikis.each do |wiki| %>
    <tr>
      <td><%= link_to wiki.title, wiki %></td>
      <td><%= wiki.public ? "public" : "private" %>
      <% if can? :update, @wiki %>
        <td> <%= link_to "edit", edit_wiki_path(wiki), class: 'button' %> </td>
      <% end %>
    </tr>
  <% end %>
</table> 

app/views/wikis/new.html.erb
<h1>create new wiki</h1>

<div class="row">
  <div class="span-6">
    <%= form_for @wiki, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :body, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :body, rows: 8 %>
        </div>
      </div>
      <% if can? :create_private, Wiki %>
        <div class="control-group">
          <div class="controls">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private, :checked => false %>make this a private wiki<br><br>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<% if can? :update, @wiki %>
  <%= link_to "edit wiki", edit_wiki_path, class: 'button' %>
<% end %>
<% if can? :update_collaborators, @wiki %>
  <%= link_to "edit collaborators", wiki_collaborations_path(@wiki.id), class: 'button' %>
<% end %>
<% if can? :destroy, @wiki %>
  <%= link_to "delete wiki", @wiki, method: :delete, class: 'button', confirm: 'Are you sure you want to delete this wiki?' %> 
<% end %>  
<div id="theText" class = "eight columns">
  <h2><%= "#{@wiki.title} by #{@author.name}" %></h2>
  <p><%= markdown @wiki.body %></p>
</div>
<div class = "eight columns">
  <h3>Collaborators</h3>
  <table id="collaborators", class="bordered">
    <% @wiki.users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </table> 
</div>