config/routes.rb
Digginit::Application.routes.draw do

  get "collaborations/index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  
  resources :users
  resources :email_confirmations
  resources :charges
  resources :wikis do
    resources :collaborations, controller: 'wikis/collaborations' 
  end

  root to: 'welcome#index'
  match "about" => 'welcome#about', via: :get 

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>digginIt</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="sixteen columns clearfix">
        <div id="logo" class="five columns alpha">
          <h1 id="logo" style="margin-top: 20px; margin-bottom: 10px;">
            <%= image_tag image_path('logo-digginit-medium.png') %>
          </h1>
        </div>

        <div id="nav" class="eleven columns omega">
          <ul>
            <h5 id="menu" style="margin-top: 20px; margin-bottom: 10px;">
              <li><%= link_to "home", root_path %></li>
              <li><%= link_to "about", about_path %></li>
              <% if current_user %>
                <li><%= link_to "my wikis", wikis_path %></li>
                <li><%= link_to "my account", user_path(current_user) %></li>
              <% end %>
              <% if current_user %>
                <li><%= link_to "sign-out", logout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "sign-in", login_path %></li>
              <% end %>
            </h5>
          </ul>
        </div>
      </div>
      <% flash_css_class = { :notice => 'notice', :alert => 'alert'} %>
      <% flash.each do |key, msg| %>
        <div id=<%= flash_css_class[key] %> class="ten columns omega">
           <%= msg %>
        </div>
       <% end unless flash.nil? %>

      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
 </html> 